[package]
name = "raid_teams"
version = "0.1.0"
authors = ["Martin Lindström <martin.lindstrom94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
